spring:
  application:
    name: gateway
  webflux:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:///c:/static
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-controller/system 前缀
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
server:
  port: 8080