spring:
  application:
    name: sys-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER}/dms
    username: root
    password: root
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
        metadata:
          public: #只要有public键就行，不读取值

server:
  port: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
