spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER}/dms
    username: root
    password: 123456
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}

server:
  port: 0
